[phases.setup]
nixPkgs = ["php82", "php82Extensions.gmp", "composer"]

[phases.build]
cmds = ["npm install && npm run build", "composer install --optimize-autoloader --no-dev --ignore-platform-reqs"]

[start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"